// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Options = Collections['options']['schema']['_output']
export declare const options: Options

export type Classes = Collections['classes']['schema']['_output']
export declare const classes: Classes[]
